# Generated by Django 6.0.1 on 2026-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_encadrant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_stagiaire',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ETUDIANT', 'Etudiant'), ('ENTREPRISE', 'Entreprise')], default='ADMIN', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stagiaire',
        ),
    ]
