# Generated by Django 6.0.1 on 2026-02-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_entreprise_etudiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='nom_entreprise',
            new_name='nom_societe',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='ice',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur',
            field=models.CharField(default='Non spécifié', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entreprise',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL),
        ),
    ]
