# Generated by Django 6.0.1 on 2026-02-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_nom_entreprise_entreprise_nom_societe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='logo',
        ),
    ]
