# Generated by Django 6.0.1 on 2026-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_entreprise_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='cv',
            new_name='cv_file',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='competences',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ecole',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='experiences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau_etudes',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='projets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
