# Generated by Django 6.0.1 on 2026-05-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_rename_cv_etudiant_cv_file_etudiant_competences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("ETUDIANT", "Etudiant"),
                    ("ENTREPRISE", "Entreprise"),
                    ("ENCADRANT", "Encadrant"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Encadrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departement", models.CharField(max_length=100)),
                ("specialite", models.CharField(max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "ENCADRANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encadrant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
