# Generated by Django 6.0.1 on 2026-01-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='nom_etudiant',
            new_name='nom_stagiaire',
        ),
    ]
