# Generated by Django 6.0.1 on 2026-01-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_rename_nom_etudiant_candidature_nom_stagiaire'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('offre', 'nom_stagiaire'), name='unique_candidature_par_offre'),
        ),
    ]
