# Generated by Django 6.0.1 on 2026-02-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_entreprise_description_entreprise_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidature',
            name='unique_candidature_par_offre',
        ),
        migrations.AddField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom_stagiaire',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('offre', 'nom_stagiaire', 'prenom_stagiaire'), name='unique_candidature_par_offre'),
        ),
    ]
