# Generated by Django 6.0.1 on 2026-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_remove_candidature_unique_candidature_par_offre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
