# Generated by Django 6.0.1 on 2026-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_offre_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='qualites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
