# Generated by Django 6.0.1 on 2026-05-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stages", "0007_offre_formation_offre_qualites"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="score_ia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidature",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("ACCEPTEE", "Acceptée"),
                    ("REFUSEE", "Refusée"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
    ]
