# Generated by Django 6.0.1 on 2026-05-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_user_role_encadrant"),
        ("stages", "0008_candidature_score_ia_candidature_statut"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageActif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut_effective", models.DateField(blank=True, null=True)),
                ("date_fin_effective", models.DateField(blank=True, null=True)),
                (
                    "rapport_file",
                    models.FileField(blank=True, null=True, upload_to="rapports/"),
                ),
                (
                    "evaluation_encadrant",
                    models.TextField(
                        blank=True,
                        help_text="Feedback de l'encadrant académique",
                        null=True,
                    ),
                ),
                (
                    "feedback_entreprise",
                    models.TextField(
                        blank=True,
                        help_text="Feedback de l'encadrant professionnel",
                        null=True,
                    ),
                ),
                ("note_finale", models.FloatField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "candidature",
                    models.OneToOneField(
                        limit_choices_to={"statut": "ACCEPTEE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_actif",
                        to="stages.candidature",
                    ),
                ),
                (
                    "encadrant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stages_supervises",
                        to="pages.encadrant",
                    ),
                ),
            ],
        ),
    ]
