# Generated by Django 6.0.1 on 2026-05-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stages", "0009_stageactif"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageactif",
            name="remarques_encadrant",
            field=models.TextField(
                blank=True,
                help_text="Directives / remarques visibles par l'étudiant",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stageactif",
            name="sujet_valide",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stageactif",
            name="tuteur_entreprise_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="stageactif",
            name="tuteur_entreprise_nom",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="stageactif",
            name="evaluation_encadrant",
            field=models.TextField(
                blank=True, help_text="Évaluation académique de l'encadrant", null=True
            ),
        ),
        migrations.CreateModel(
            name="Livrable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_doc",
                    models.CharField(
                        choices=[
                            ("AVANCEMENT", "Rapport d'avancement"),
                            ("FINAL", "Rapport final PFE"),
                            ("ATTESTATION", "Attestation de stage"),
                            ("AUTRE", "Autre document"),
                        ],
                        default="AVANCEMENT",
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(upload_to="livrables/")),
                ("date_depot", models.DateTimeField(auto_now_add=True)),
                (
                    "telecharge",
                    models.BooleanField(
                        default=False,
                        help_text="Marqué True lorsque l'encadrant télécharge le fichier",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livrables",
                        to="stages.stageactif",
                    ),
                ),
            ],
        ),
    ]
