# Generated by Django 6.0.1 on 2026-05-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stages", "0010_stageactif_remarques_encadrant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageactif",
            name="note_assiduite",
            field=models.IntegerField(default=0, help_text="Note sur 5"),
        ),
        migrations.AddField(
            model_name="stageactif",
            name="note_integration",
            field=models.IntegerField(default=0, help_text="Note sur 5"),
        ),
        migrations.AddField(
            model_name="stageactif",
            name="note_technique",
            field=models.IntegerField(default=0, help_text="Note sur 5"),
        ),
    ]
